language: go

addons:
  postgresql: '9.6'

go:
- "1.10"

before_install:
  - wget https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-6.2.3.deb && sudo dpkg -i --force-confnew elasticsearch-6.2.3.deb
  - sudo service elasticsearch start
  - sleep 10

before_script:
  - psql -U postgres -c "CREATE DATABASE elastic_test;"

script:
- go test -p=1 -coverprofile=coverage.text -covermode=atomic github.com/nyaruka/rp-indexer/...

after_success:
- bash <(curl -s https://codecov.io/bash)
- rm coverage.text
- test -n "$TRAVIS_TAG" && curl -sL https://git.io/goreleaser | bash

