name: CI
on: [push, pull_request]
env:
  go-version: "1.22.x"
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        elastic-port: [9207, 9208]
    
    services:
      postgres:
        image: postgres:14-alpine
        env:
          POSTGRES_DB: indexer_test
          POSTGRES_USER: indexer_test
          POSTGRES_PASSWORD: temba
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
      elastic7:
        image: elasticsearch:7.17.9
        ports:
          - 9207:9200
        env:
          discovery.type: single-node
      elastic8:
        image: elasticsearch:8.13.4
        ports:
          - 9208:9200
        env:
          discovery.type: single-node
          xpack.security.enabled: false

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ env.go-version }}

      - name: Setup environment
        run: |
          echo "INDEXER_ELASTIC_URL=http://localhost:${{ matrix.elastic-port }}" >> "$GITHUB_ENV"

      - name: Run tests
        run: go test -p=1 -coverprofile=coverage.text -covermode=atomic ./...

      - name: Upload coverage
        if: success()
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: true

  release:
    name: Release
    needs: [test]
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install Go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ env.go-version }}

      - name: Publish release
        uses: goreleaser/goreleaser-action@v4
        with:
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
